### ISSUE TITLE
Fix more PHP 8.4 deprecation erros

### ISSUE THREAD

**Issue by MurzNN** [commercetools/commercetools-sdk-php-v2#317]
In the PR https://github.com/commercetools/commercetools-sdk-php-v2/pull/301 some deprecation errors were fixed. I updated to the 10.12.0 release, but still having PHP deprecation issues:
```
Deprecated: {closure:Commercetools\Client\MiddlewareFactory::createRetryNAMiddleware():69}(): Implicitly marking parameter $response as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/web/vendor/commercetools/commercetools-sdk/lib/commercetools-base/src/Client/MiddlewareFactory.php on line 74
```
```
Deprecated: Commercetools\Api\Client\Resource\ResourceByProjectKey::__construct(): Implicitly marking parameter $client as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/web/vendor/commercetools/commercetools-sdk/lib/commercetools-api/src/Client/Resource/ResourceByProjectKey.php on line 24
```
There are more than 1000 places where we should fix this. But seems these files are auto-generated, so seems we need to fix this in the generator, and then - regenerate the files.

**Comment by jenschude** [comment]
This should be fixed with #322 now

**Comment by stevekarsch** [comment]
It looks like the 10.13.0 release fixed a number of these issues but I'm still seeing:

`PHP Deprecated:  Commercetools\Client\ClientCredentials::__construct(): Implicitly marking parameter $scope as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/commercetools/commercetools-sdk/lib/commercetools-base/src/Client/ClientCredentials.php on line 41
PHP Deprecated:  Commercetools\Client\CachedTokenProvider::__construct(): Implicitly marking parameter $cacheKey as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/commercetools/commercetools-sdk/lib/commercetools-base/src/Client/CachedTokenProvider.php on line 33`

**Comment by jenschude** [comment]
As psalm wasn't reporting these deprecations i now added phpstan for finding the missing ones.

Released 10.13.1 which should now remove all of them
